title: Chipprogrammers
description: Tech Blog
author: Chipprogrammer
logo: /static/img/avatar.png
github: https://github.com/chipprogrammers
about: Arun&rsquo;s and Ideas

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: https-chipprogrammers-github-io-pimate
# google_analytics: UA-72862926-1

share:
  twitter_username: ARUNKSOMAN2
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
